language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id:
	secure: $accesskey
  secret_access_key:
	secure: $secretkey
  region: "eu-west-2"
  app: "travistest"
  env: "travistest-dev"
  bucket_name: "travistest-eu-west-2-test"
  on:
    branch: master
