language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "P/qtjVYsmgws8b7/cKjKnF5Lo6dvCtp7IJMun84afjMG9taUIW5FxYKkda9RD4DhrmGXTbortt8isWEkh7INht/x8z3GEypgIk+J/b3GuhaKC8ooGrXFJhkupWV8oRuCqV7EYHJZIgYnepCYSV0frYucNEffNk6XRvavCCTfoTywoFXwdPkURyGAHTkwTB/OudvP51qPoIXS/E8E/LhJNj5lmw41Q4OQNTzIo8i8lOi+NgCmgmFLO72488eIScaUwA59OFV+uw1vfDwUsedLetvis0aiUUEb4735Hy5A+RKsG0DdwAHeqem1Ojbu3OfUAkw0KLXvhuk/ZVxgGdErb697cZsV0VK4jDkb8GzWngcOkR+bOuvhtJHGMclFlwLl2xDNRiwpaJYRBdJRCwoTxOnMq+i4Zh5icRf/gZx6PnS9NoKW5LJJQ7I8OqTmLPE7BbH6lt+E4rNZ9B8p25HKMSy6rl5j/DtzXvoQ8vBw29VHtah7WNKAI7JK37Gk6wfufRPPd9ihBpzh7bb8B5Wck82IrfYvGaHZ74AZdFvAS7xuxZ/xpj5AIK/4fcQoCeZU+n3eGmlC5puo4a2ib4pqmeWB6U4QwsEZWcn8KjPCgYFeLmdTxQ381rPDs2ETe5DuQTjXEeT40ji67fbhfaBNDvS9D9CJj3KZrnZT559lSGs="
  secret_access_key:
    secure: "ML7rr/HRJpVXyrGiOAJSD2MsE9QfgcFtDCHuxWNAXAhD6AAkZ+nzKa3Yv0Qw5pS6MJqYFl3vykcIMbuE9zUlRl/y9FsaHlGlk63IjotWsdEwP9Oo5VzaMNEnyaAsHETFZ2GpuF4ft5j7uBPdy40lTXtYu/bAvukQprz+1FonxjlIF/U8SzdM7kggE/iqTN+KtSSDxN3XJli+nb3v8aKlOfor+cLRmYHeEg8jQuD1SY+aV3LwSdBE34gA8Krqt20ebCMXrEa5afHhJNdP0K5GBQ/hiGkJx8Va17vklgXjkE7vEW2l3ITy4GUhOVVNLhVTSdYfjQJdeD290kxQ/sccyWQvm9+/oBrXK2E1qUJcNdm/xe0XSHlt7QHMxSWmfPTY25qeT346nVcKdoeFaakZivadFsfAORJRJJSzbRZLwoHZehnjJIkTWnEwJrWoOB/Eump5w8TgOCq6AJ9dGuT+47g0agGzomfA0580pqbUe8mr7Jf3ygoitGsQgHFRqZumsnYscJJE95Qx+IwoavGXh9me1B0RvrUc7tBXcGqPEpSQfuWSiObAA2tBZALn2dCL9wEh6Bikwp3takx7Iu/7hcDhW6cGb26bZ6P3lQ3f/CLkzf3WrfiIa0yd8wxJN+EoHP6V57Zn2MnMaEe/Nlz4YiWaXvZg2hGSaw7Vp3rWWec="
  region: "eu-west-2"
  app: "travistest"
  env: "travistest-dev"
  bucket_name: "elasticbeanstalk-eu-west-2-069653090426"
  on:
    branch: master
