language: node_js
node_js:
- '8'
sudo: required
services:
- docker
after_deploy:
- echo "done deploying"
deploy:
  provider: elasticbeanstalk
  access_key_id: $accesskey
  secret_access_key: $secretkey
  region: eu-west-2
  app: travistest
  env: travistest-stage
  bucket_name: travistest-eu-west-2-test
  on:
    branch: stage
