language: node_js
node_js:
- '8'
sudo: required
services:
- docker
after_deploy:
- echo "done deploying"
deploy:
  provider: elasticbeanstalk
  access_key_id:
	secure: "H8TIJr1DPw4AIcThUywivcnqDzp8gG+aDHzZ2BbgPGs6zKLWKiyhJlXs9hztIFQGJMQ4k8Lg6YE3XYLXxDzM17a40a4k7AgeF00cSSObUNLeIMrqLh5+zVr+lXDC2baMwBCO8l/sUkhEu3kp5EL/6PZhClI1d4DznyGuEXj+YH87uAqgcuiNh5JMqKkuMUeGlfSrNhP5qp5+z12JaHWk8BtJiWKRhTtfZJmgK36dlcy7Zz7g2GBY+N0CgAPDfm2RDZj+nuOdjvSpUikMY2lwkFQlfeL61idqwD8YMHQfAXI4OuYj5wgwK7cZ5EJoXM9r1GD4/Z5ytXZv1dzKwahL9tYrXoTGFdv8tqDrlUWERWVT/dP2pmiovTfpUR2bWqPK2n30fs1G7bP5HBEqowThhvonRTdLwybj86Xi/0oxNc+pcYJwk5RuSMcGaGIIGLWqfxVFZP79+1fGE2Fjx1bYyExj7zGUCPw/KKSbGnL/dkstqkmP+NTiSot1P2XEPPlOHVoIHRPzgL2qEs1NqSyATBtugrzAOTVoiTFmExOXZYSBt+6T+ic/0xuO1XE5kTpM5/fi+TM9D37JzoQlADTKfIeCIp2XbOqR1nmQsfLztmk2r3wJRPV2x6zaHA96kXqgacQn0TvCjwAXQys4/MfhzEJzgybMdLxL9GvsTkp8ACM="
  secret_access_key:
	secure: "klVbUtCewlB48ZcosadJgIgGD8oNLfyX0bc0tL0UUtDFPdXvd/WoffPVXMVZXDsYbFd860W/hTWvYkNKmI8eFJYJYrfRULExqUFMxXzENzO6zv/2Lr7zp2PrlK+0LJ01kTyjwcj6n+mFmjSd95tvRFo4a3F3ykJEf9jiUI++RWgQ3UPKaoekRPtwDbjxc8FNCkdExJMEx10ddHjxWakD2BM1oRfHcKo1gqDRoU2v5SHgK+kdAi35lIjRS4xBinjvzVujU4cQya/ySCF3xpu3UQqwtAp+NrUV06rQQinBlxeAVbty0/BjF60O0U9CQ27WUUPyiUlpRkTfEN6lnkfN2xqP4wT9S8f7H1OM9mH41WzNAuVIXqB3RnslaMnNXem5iVYVtFQTBk92ay2Je/scJKEb4O/noy2j5vxoo/dqaxuuVWNUUGeMqZsG1XsSk9681IruJCU4IqdcHdhkLu5H4OVfEFrpVZ/szN5/xJqxn6SmT2h1KldcAB6D4d+zmmA6kNLydSu9QxgBZtjuBE5OmFXhpKVWfvBXNLja83/715jIAxOQwku4iRXQWRPNy0b0AJdUgVm1bMPG3jrki0VqvNcUcSIAR5iyu0uTwWKBzS+Hyf5m50QcOTLgJXs3RUBWQH1T4LfeQSr+uk7KMtfSG2GUuTc+PigJYlW0Jk1CTDk="
  region: eu-west-2
  app: travistest
  env: travistest-dev
  bucket_name: travistest-eu-west-2-test
  on:
    branch: master
